export const EXERCISE_MAP: Record<string, string> = {
  // ==================== CHEST (60+) ====================
  "barbell flat bench press": "https://media1.tenor.com/m/kpJH4zjuPF8AAAAC/supino.gif",
  "dumbbell flat bench press": "",
  "incline barbell bench press": "",
  "incline dumbbell bench press": "",
  "decline barbell bench press": "",
  "decline dumbbell bench press": "",
  "dumbbell chest fly": "",
  "incline dumbbell fly": "",
  "decline dumbbell fly": "",
  "cable chest fly": "",
  "high to low cable fly": "",
  "low to high cable fly": "",
  "pec deck fly": "",
  "machine chest press": "",
  "incline machine chest press": "",
  "push up": "",
  "diamond push up": "",
  "wide grip push up": "",
  "incline push up": "",
  "decline push up": "",
  "archer push up": "",
  "chest dip": "",
  "weighted chest dip": "",
  "assisted chest dip": "",
  "cable crossover": "",
  "svend press": "",
  "plate press": "",
  "hex press": "",

  // ==================== LEGS / LOWER BODY (80+) ====================
  "barbell back squat": "",
  "barbell front squat": "",
  "barbell overhead squat": "",
  "high bar squat": "",
  "low bar squat": "",
  "safety bar squat": "",
  "hack squat": "",
  "leg press": "",
  "45 degree leg press": "",
  "horizontal leg press": "",
  "dumbbell goblet squat": "",
  "dumbbell front squat": "",
  "dumbbell sumo squat": "",
  "dumbbell walking lunge": "",
  "dumbbell reverse lunge": "",
  "dumbbell bulgarian split squat": "",
  "barbell bulgarian split squat": "",
  "romanian deadlift": "",
  "conventional deadlift": "",
  "sumo deadlift": "",
  "trap bar deadlift": "",
  "deficit deadlift": "",
  "leg extension": "",
  "seated leg curl": "",
  "lying leg curl": "",
  "standing leg curl": "",
  "hip thrust": "",
  "barbell hip thrust": "",
  "dumbbell hip thrust": "",
  "glute bridge": "",
  "single leg glute bridge": "",
  "standing calf raise": "",
  "seated calf raise": "",
  "leg press calf raise": "",
  "donkey calf raise": "",
  "sissy squat": "",
  "pistol squat": "",
  "step up": "",
  "box jump": "",

  // ==================== BACK (70+) ====================
  "barbell bent over row": "",
  "dumbbell bent over row": "",
  "dumbbell single arm row": "",
  "seated cable row": "",
  "standing cable row": "",
  "t bar row": "",
  "landmine row": "",
  "lat pulldown": "",
  "wide grip lat pulldown": "",
  "close grip lat pulldown": "",
  "neutral grip lat pulldown": "",
  "pull up": "",
  "wide grip pull up": "",
  "close grip pull up": "",
  "neutral grip pull up": "",
  "chin up": "",
  "weighted pull up": "",
  "assisted pull up": "",
  "face pull": "",
  "straight arm pulldown": "",
  "cable pullover": "",
  "dumbbell pullover": "",
  "barbell shrug": "",
  "dumbbell shrug": "",
  "kelso shrug": "",
  "back extension": "",
  "hyperextension": "",
  "good morning": "",

  // ==================== SHOULDERS (60+) ====================
  "barbell overhead press": "",
  "dumbbell overhead press": "",
  "seated dumbbell shoulder press": "",
  "arnold press": "",
  "machine shoulder press": "",
  "dumbbell lateral raise": "",
  "cable lateral raise": "",
  "egyptian lateral raise": "",
  "dumbbell front raise": "",
  "plate front raise": "",
  "rear delt fly": "",
  "bent over rear delt fly": "",
  "cable rear delt fly": "",
  "upright row": "",
  "barbell upright row": "",
  "dumbbell upright row": "",
  "bus driver": "",
  "external rotation": "",
  "internal rotation": "",

  // ==================== ARMS - BICEPS (50+) ====================
  "barbell bicep curl": "",
  "ez bar curl": "",
  "dumbbell bicep curl": "",
  "hammer curl": "",
  "incline dumbbell curl": "",
  "preacher curl": "",
  "concentration curl": "",
  "cable bicep curl": "",
  "rope hammer curl": "",
  "zottman curl": "",
  "drag curl": "",
  "21s curl": "",

  // ==================== ARMS - TRICEPS (40+) ====================
  "tricep overhead extension": "",
  "dumbbell overhead tricep extension": "",
  "skull crusher": "",
  "ez bar skull crusher": "",
  "close grip bench press": "",
  "tricep pushdown": "",
  "rope tricep pushdown": "",
  "v bar tricep pushdown": "",
  "tricep dip": "",
  "bench dip": "",
  "kickback": "",
  "jm press": "",

  // ==================== CORE / ABS (60+) ====================
  "plank": "",
  "side plank": "",
  "russian twist": "",
  "hanging leg raise": "",
  "hanging knee raise": "",
  "captains chair leg raise": "",
  "ab wheel rollout": "",
  "cable crunch": "",
  "decline sit up": "",
  "bicycle crunch": "",
  "mountain climber": "",
  "flutter kick": "",
  "v up": "",
  "dragon flag": "",
  "l sit": "",

  // ==================== FULL BODY / COMPOUND / OLYMPIC (50+) ====================
  "clean and jerk": "",
  "power clean": "",
  "hang clean": "",
  "snatch": "",
  "power snatch": "",
  "thruster": "",
  "kettlebell swing": "",
  "burpee": "",
  "turkish get up": "",
  "farmer carry": "",
  "suitcase carry": "",
  "zercher squat": "",
  "landmine press": "",
  "landmine twist": "",

  // ==================== MORE VARIATIONS & ACCESSORIES (100+) ====================
  "incline dumbbell hammer curl": "",
  "reverse grip bench press": "",
  "guillotine press": "",
  "spoto press": "",
  "pin press": "",
  "pause bench press": "",
  "floor press": "",
  "jefferson deadlift": "",
  "stiff leg deadlift": "",
  "single leg romanian deadlift": "",
  "copenhagen plank": "",
  "adductor machine": "",
  "abductor machine": "",
  "pec deck rear fly": "",
  "wrist curl": "",
  "reverse wrist curl": "",
  "neck curl": "",
  "neck extension": "",
  // ... aur bhi add kar sakte hain

  // Total ~550+ entries possible by expanding further
    // ==================== EXTRA CHEST VARIATIONS ====================
  "smith machine flat bench press": "",
  "smith machine incline bench press": "",
  "neutral grip dumbbell bench press": "",
  "single arm dumbbell bench press": "",
  "deficit push up": "",
  "clapping push up": "",
  "one arm push up": "",
  "machine fly": "",
  "standing cable chest press": "",
  "incline cable chest press": "",

  // ==================== EXTRA LEGS / LOWER BODY ====================
  "smith machine squat": "",
  "v squat": "",
  "belt squat": "",
  "front foot elevated split squat": "",
  "rear foot elevated split squat": "",
  "curtsy lunge": "",
  "lateral lunge": "",
  "dumbbell sumo deadlift": "",
  "snatch grip deadlift": "",
  "rack pull": "",
  "block pull": "",
  "nordic hamstring curl": "",
  "glute ham raise": "",
  "reverse hyperextension": "",
  "single leg leg extension": "",
  "single leg leg curl": "",
  "tibialis raise": "",
  "toe walk": "",
  "jump squat": "",
  "dumbbell calf jump": "",

  // ==================== EXTRA BACK ====================
  "meadows row": "",
  "pendlay row": "",
  "helms row": "",
  "incline dumbbell row": "",
  "chest supported dumbbell row": "",
  "chest supported t bar row": "",
  "single arm lat pulldown": "",
  "supinated lat pulldown": "",
  "behind neck lat pulldown": "",
  "commando pull up": "",
  "l sit pull up": "",
  "muscle up": "",
  "inverted row": "",
  "smith machine row": "",
  "rope face pull": "",
  "band pull apart": "",
  "scapular pull up": "",

  // ==================== EXTRA SHOULDERS ====================
  "seated barbell shoulder press": "",
  "standing barbell shoulder press": "",
  "landmine shoulder press": "",
  "kettlebell shoulder press": "",
  "single arm dumbbell shoulder press": "",
  "leaning lateral raise": "",
  "cable y raise": "",
  "dumbbell y raise": "",
  "overhead plate raise": "",
  "dumbbell circle raise": "",
  "w raise": "",
  "bent over lateral raise": "",
  "cable upright row": "",
  "smith machine upright row": "",
  "shoulder external rotation cable": "",
  "shoulder internal rotation cable": "",

  // ==================== EXTRA BICEPS ====================
  "reverse barbell curl": "",
  "reverse ez bar curl": "",
  "dumbbell reverse curl": "",
  "cable reverse curl": "",
  "supinated dumbbell curl": "",
  "prone incline dumbbell curl": "",
  "spider curl": "",
  "bayesian cable curl": "",
  "cable curl 21s": "",
  "band bicep curl": "",

  // ==================== EXTRA TRICEPS ====================
  "single arm tricep pushdown": "",
  "overhead cable tricep extension": "",
  "single arm overhead tricep extension": "",
  "bodyweight tricep extension": "",
  "diamond dip": "",
  "parallel bar tricep dip": "",
  "french press": "",
  "lying dumbbell tricep extension": "",
  "tricep kickback cable": "",
  "band tricep pushdown": "",

  // ==================== EXTRA CORE / ABS ====================
  "hollow body hold": "",
  "dead bug": "",
  "bird dog": "",
  "pallof press": "",
  "stir the pot": "",
  "ab roller plank": "",
  "toes to bar": "",
  "windshield wiper": "",
  "hanging windshield wiper": "",
  "side plank hip dip": "",
  "woodchopper": "",
  "cable woodchopper": "",
  "garhammer raise": "",
  "reverse crunch": "",
  "heel tap": "",
  "leg raise hold": "",

  // ==================== KETTLEBELL / DUMBBELL SPECIFIC ====================
  "kettlebell goblet squat": "",
  "kettlebell clean": "",
  "kettlebell jerk": "",
  "kettlebell snatch": "",
  "kettlebell windmill": "",
  "kettlebell turkish get up": "",
  "kettlebell bottoms up press": "",
  "single arm kettlebell swing": "",
  "double kettlebell swing": "",
  "kettlebell front rack carry": "",

  // ==================== MORE COMPOUND & OLYMPIC ====================
  "push press": "",
  "push jerk": "",
  "split jerk": "",
  "hang snatch": "",
  "dumbbell clean and press": "",
  "dumbbell snatch": "",
  "medicine ball slam": "",
  "medicine ball rotational throw": "",
  "battle rope wave": "",
  "battle rope slam": "",
  "sled push": "",
  "sled pull": "",
  "yoke walk": "",
  "atlas stone lift": "",

  // ==================== ACCESSORIES & SMALL MUSCLES ====================
  "dumbbell wrist curl": "",
  "dumbbell reverse wrist curl": "",
  "finger curl": "",
  "pinch grip hold": "",
  "neck harness curl": "",
  "neck harness extension": "",
  "trap bar shrug": "",
  "dumbbell external rotation": "",
  "dumbbell internal rotation": "",
  "face pull with rope": "",
  "overhead tricep stretch": "",
  "cat cow pose": "",
  "bird dog plank": "",
  "superman hold": "",
  "prone cobra": "",
  "wall angel": "",
  "scapular wall slide": "",
  "cuban press": "",
  "band dislocate": "",

  // ==================== MACHINE & CABLE ONLY ====================
  "smith machine deadlift": "",
  "smith machine bench press": "",
  "smith machine overhead press": "",
  "cable squat": "",
  "cable hip abduction": "",
  "cable hip adduction": "",
  "cable kickback": "",
  "cable pull through": "",
  "rotary torso machine": "",
  "back extension machine": "",

};